// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFt8NaED2p9gRoBGktq1MAgxo8fFf7ZxA',
    appId: '1:219917704477:web:348637f18fdd113b7395f4',
    messagingSenderId: '219917704477',
    projectId: 'kud-shop-flutter',
    authDomain: 'kud-shop-flutter.firebaseapp.com',
    storageBucket: 'kud-shop-flutter.firebasestorage.app',
    measurementId: 'G-P7Q09ELLNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOykSIXKJ5QZutb_yTc9-UrPPwJuNunTo',
    appId: '1:219917704477:android:591c27e24d8cb68a7395f4',
    messagingSenderId: '219917704477',
    projectId: 'kud-shop-flutter',
    storageBucket: 'kud-shop-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMzRclunCnWjiCs0jq8R9lsxSk095hO4',
    appId: '1:219917704477:ios:bcc5493a11c906237395f4',
    messagingSenderId: '219917704477',
    projectId: 'kud-shop-flutter',
    storageBucket: 'kud-shop-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiPlayground',
  );

}